name: Unit testing

on: [push, pull_request]

jobs:
  test:
    name: Test on .NET Core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use .NET 3.1.102
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
        
    - name: Build
      run: dotnet build --configuration Debug
      
    - name: Run tests
      run: dotnet test
